@IssueTrackerApi_HostAddress = http://localhost:1336

GET {{IssueTrackerApi_HostAddress}}/issues/
Accept: application/json

###

GET {{IssueTrackerApi_HostAddress}}/issues/507b5059-3418-4672-be13-c27d901c1afe
Accept: application/json

###

POST {{IssueTrackerApi_HostAddress}}/issues
Accept: application/json
Content-Type: application/json

{
  "software": "Pancake",
  "description": "Syrup"
}

###